-- Seed data for major cultural sites across Italy, Germany, France, England, and Spain

INSERT INTO cultural_sites (name, description, historical_context, cultural_significance, location_country, location_city, site_type, construction_date, architect_artist, image_keywords, fun_facts, visitor_tips) VALUES

-- Italy
('Colosseum', 'The largest amphitheater ever built, capable of holding 80,000 spectators', 'Built during the Flavian dynasty between 70-80 AD as a venue for gladiatorial contests and public spectacles', 'Symbol of Imperial Rome and architectural innovation, UNESCO World Heritage Site', 'Italy', 'Rome', 'monument', '70-80 AD', 'Unknown', ARRAY['colosseum', 'amphitheater', 'rome', 'arches', 'stone', 'ancient'], ARRAY['Had a complex system of elevators and trapdoors', 'Could be flooded for naval battle reenactments', 'Free admission on the first Sunday of each month'], 'Visit early morning or late afternoon to avoid crowds. Book skip-the-line tickets in advance.'),

('Mona Lisa', 'Leonardo da Vinci''s masterpiece portrait, famous for her enigmatic smile', 'Painted between 1503-1519 during the Italian Renaissance', 'Most famous painting in the world, epitome of Renaissance art', 'France', 'Paris', 'artwork', '1503-1519', 'Leonardo da Vinci', ARRAY['mona lisa', 'leonardo', 'portrait', 'smile', 'renaissance'], ARRAY['Stolen in 1911 and missing for two years', 'Protected by bulletproof glass since 1956', 'Only 77cm × 53cm in size'], 'Located in the Louvre Museum. Arrive early or book timed entry tickets.'),

('Neuschwanstein Castle', 'Fairy-tale castle built by King Ludwig II of Bavaria', 'Constructed from 1869-1886 as a retreat for the reclusive king', 'Inspiration for Disney''s Sleeping Beauty Castle, symbol of 19th-century Romanticism', 'Germany', 'Schwangau', 'castle', '1869-1886', 'Eduard Riedel', ARRAY['neuschwanstein', 'castle', 'bavaria', 'fairy tale', 'ludwig'], ARRAY['Only 14 rooms were completed out of 200 planned', 'Ludwig II died mysteriously before completion', 'Receives over 1.3 million visitors annually'], 'Book tickets online in advance. Best photographed from Mary''s Bridge (Marienbrücke).'),

('Big Ben', 'Iconic clock tower of the Palace of Westminster', 'Completed in 1859, officially named Elizabeth Tower since 2012', 'Symbol of London and British parliamentary democracy', 'England', 'London', 'building', '1859', 'Augustus Pugin', ARRAY['big ben', 'clock tower', 'westminster', 'london', 'parliament'], ARRAY['The name refers to the largest bell, not the tower', 'Chimes every 15 minutes', 'Currently under restoration until 2021'], 'Best viewed from Westminster Bridge or Parliament Square. Tours available for UK residents.'),

('Sagrada Familia', 'Antoni Gaudí''s unfinished basilica masterpiece', 'Construction began in 1882 and continues today', 'UNESCO World Heritage Site, symbol of Barcelona and Modernist architecture', 'Spain', 'Barcelona', 'church', '1882-present', 'Antoni Gaudí', ARRAY['sagrada familia', 'gaudi', 'basilica', 'barcelona', 'modernist'], ARRAY['Expected completion around 2026', 'Funded entirely by donations and ticket sales', 'Each facade tells a different story of Christ''s life'], 'Book timed entry tickets online. Consider the audio guide to understand Gaudí''s symbolism.'),

-- Additional major sites
('Eiffel Tower', 'Iron lattice tower and symbol of Paris', 'Built for the 1889 World''s Fair as entrance arch', 'Global icon of France and feat of 19th-century engineering', 'France', 'Paris', 'monument', '1889', 'Gustave Eiffel', ARRAY['eiffel tower', 'paris', 'iron', 'lattice', 'tower'], ARRAY['Was supposed to be temporary', 'Grows 6 inches in summer due to thermal expansion', 'Painted every 7 years to prevent rust'], 'Visit at sunset for golden hour photos. Book elevator tickets in advance.'),

('Sistine Chapel', 'Papal chapel famous for Michelangelo''s ceiling frescoes', 'Built 1473-1481, ceiling painted 1508-1512', 'Site of papal conclaves and masterpiece of Renaissance art', 'Italy', 'Vatican City', 'church', '1473-1481', 'Michelangelo (ceiling)', ARRAY['sistine chapel', 'michelangelo', 'vatican', 'ceiling', 'fresco'], ARRAY['Michelangelo painted lying on his back', 'Contains over 300 figures', 'Photography is strictly forbidden'], 'Part of Vatican Museums tour. Book skip-the-line tickets. Silence is required inside.'),

('Tower Bridge', 'Victorian bascule and suspension bridge', 'Opened in 1894 after 8 years of construction', 'Iconic symbol of London and engineering marvel', 'England', 'London', 'building', '1894', 'Sir Horace Jones', ARRAY['tower bridge', 'london', 'thames', 'bascule', 'victorian'], ARRAY['Often confused with London Bridge', 'Bascules still open about 1000 times per year', 'Glass floor walkway added in 2014'], 'Visit the glass floor walkways and Victorian Engine Rooms. Check bridge lift times online.'),

('Brandenburg Gate', 'Neoclassical triumphal arch and symbol of Berlin', 'Completed in 1791, inspired by the Acropolis in Athens', 'Symbol of German reunification and European unity', 'Germany', 'Berlin', 'monument', '1791', 'Carl Gotthard Langhans', ARRAY['brandenburg gate', 'berlin', 'neoclassical', 'quadriga', 'arch'], ARRAY['Topped by the Quadriga sculpture', 'Was part of the Berlin Wall division', 'Illuminated in different colors for special events'], 'Best photographed from Pariser Platz. Free to visit and accessible 24/7.'),

('Alhambra', 'Moorish palace and fortress complex', 'Built during 13th and 14th centuries by Nasrid dynasty', 'Pinnacle of Moorish art in Europe, UNESCO World Heritage Site', 'Spain', 'Granada', 'building', '13th-14th century', 'Nasrid architects', ARRAY['alhambra', 'granada', 'moorish', 'palace', 'nasrid'], ARRAY['Name means "The Red One" in Arabic', 'Contains intricate geometric patterns and calligraphy', 'Inspired Washington Irving''s "Tales of the Alhambra"'], 'Book tickets well in advance online. Visit during golden hour for best lighting.');
